decentraland/marketplace-favorites-server

package-lock.json, package.json, src/components.ts, src/metrics.ts, src/ports/fetch/component.ts, test/components.ts
This PR implements tracing in the service.
=> feat: Implement tracing

package-lock.json, package.json, src/components.ts
This PR adds the request logger component to log any incoming request.
=> feat: Add request logger

src/adapters/picks/picks.ts, src/controllers/handlers/picks-handlers.ts, src/controllers/routes.ts, src/logic/ethereum/validations.ts, src/ports/picks/component.ts, src/ports/picks/types.ts, test/components.ts, test/unit/ethereum-logic.spec.ts, test/unit/picks-adapters.spec.ts, test/unit/picks-component.spec.ts, test/unit/picks-handler.spec.ts
This PR adds the picks stats endpoints to retrieve the stats of various item ids.
=> feat: Add the picks stats endpoint

src/adapters/lists/lists.ts, src/adapters/picks/picks.ts, src/ports/picks/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-handler.spec.ts, test/unit/picks-adapters.spec.ts, test/unit/picks-handler.spec.ts
This PR changes all counts from strings to integers.
=> fix: Make all counts be integers

src/ports/lists/component.ts, test/unit/lists-component.spec.ts
This PR adds logs that record the update of the VP of an user picking an item.
=> feat: Add VP logging

src/controllers/handlers/picks-handlers.ts, src/controllers/routes.ts, src/ports/picks/component.ts, src/ports/picks/types.ts, test/unit/picks-component.spec.ts, test/unit/picks-handler.spec.ts
Related to https://github.com/decentraland/marketplace/issues/1567
=> feat: Sort picks by the logged user

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-handler.spec.ts
This PR returns the date of creation of the picks.
=> feat: Return created at when returning picks

src/ports/picks/component.ts, test/unit/picks-component.spec.ts
This PR fixes the issue where the users where not seeing their picks if they didn't have enough VP.
=> fix: Count requested user's picks if it has no VP

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, src/controllers/handlers/lists-handlers.ts, src/controllers/routes.ts, src/ports/lists/component.ts, src/ports/lists/types.ts, test/components.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Add get lists endpoint

src/adapters/lists/lists.ts, src/controllers/handlers/lists-handlers.ts, src/controllers/routes.ts, src/ports/lists/component.ts, src/ports/lists/errors.ts, src/ports/lists/types.ts, src/types.ts, test/components.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts, test/unit/picks-component.spec.ts
=> feat: Add create list endpoint

src/controllers/handlers/lists-handlers.ts, src/controllers/routes.ts, src/ports/lists/component.ts, src/ports/lists/errors.ts, src/ports/lists/types.ts, test/components.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Add DELETE list endpoint

src/migrations/1677778846950_lists-and-picks.ts, src/migrations/1683320488882_acl.ts
This PR creates the ACL table.
Closes #94
=> feat: Add ACL table

src/controllers/handlers/lists-handlers.ts, src/migrations/1677778846950_lists-and-picks.ts, src/migrations/1683550567371_add-created-at-column-to-lists.ts, src/ports/lists/component.ts, src/ports/lists/types.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Sort lists by creation or name

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, src/controllers/handlers/lists-handlers.ts, src/controllers/routes.ts, src/ports/access/component.ts, src/ports/lists/component.ts, src/ports/lists/errors.ts, src/ports/lists/types.ts, src/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Add get list endpoint

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, src/controllers/handlers/lists-handlers.ts, src/ports/lists/component.ts, src/ports/lists/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Retrieve items count when fetching a list

src/components.ts, src/controllers/handlers/lists-handlers.ts, src/controllers/handlers/picks-handlers.ts, src/controllers/routes.ts, src/ports/items/component.ts, src/ports/items/errors.ts, src/ports/items/index.ts, src/ports/items/types.ts, src/ports/lists/component.ts, src/ports/lists/errors.ts, src/ports/lists/index.ts, src/ports/lists/types.ts, src/ports/picks/component.ts, src/ports/picks/errors.ts, src/ports/picks/index.ts, src/ports/picks/schemas.ts, src/ports/picks/types.ts, src/ports/vp/queries.ts, src/types.ts, test/components.ts, test/unit/items-component.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts, test/unit/picks-component.spec.ts, test/unit/picks-handler.spec.ts, test/unit/schema-validator.spec.ts, test/unit/vp-queries.spec.ts
=> feat: Adding/Removing item to/from lists in bulk endpoint

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, src/ports/lists/component.ts, src/ports/lists/queries.ts, src/ports/lists/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts, test/unit/lists-handler.spec.ts
=> feat: Add isPrivate property when returning lists

src/ports/lists/component.ts, test/unit/lists-component.spec.ts
=> feat: Merge the result of the creation with the privacy flag

src/controllers/handlers/lists-handlers.ts, src/controllers/routes.ts, src/ports/lists/types.ts, test/unit/lists-handler.spec.ts
Related to https://github.com/decentraland/marketplace/issues/1793
=> fix: Set optional authentication for get picks by list id

src/ports/lists/component.ts, test/unit/lists-component.spec.ts
=> fix: Sorting by updateAt with the nulls at the end

src/adapters/lists/lists.ts, src/adapters/lists/types.ts, src/ports/lists/queries.ts, src/ports/lists/types.ts, test/unit/lists-adapters.spec.ts, test/unit/lists-component.spec.ts
Related to https://github.com/decentraland/marketplace/issues/1893
=> feat: Return preview items on get list

.env.spec, package-lock.json, package.json, src/ports/snapshot/component.ts, src/ports/snapshot/constants.ts
this pr shouldn't be merged until the migration is done
=> feat: replace goerli with sepolia

.env.default, src/components.ts
This PR makes the favorites allow regex CORS origins.
=> feat: Allow regex CORS origins
